### ISSUE TITLE
Read Me

### ISSUE THREAD

**Issue by KewTeacher** [Comp-Sci-Principles-2018-19/project-AzraBetul#1]
This is looking much better now. 

Problem: Add something about people eating TOO MUCH food as well

Big Idea: Edit this to make it more readable. 

1st iteration: Love it!

**Comment by AzraBetul** [comment]
okay I will Mr. Arson thank u

**Comment by AzraBetul** [comment]
I fixed it. Mr. Arson. I added some sentences on the problem section.

**Comment by KewTeacher** [comment]
I made some notes in your readme.

**Comment by AzraBetul** [comment]
i fixed the whole big fat idea. I hope you like it.

**Comment by AzraBetul** [comment]
i also put some sentences in the problem section too

**Comment by AzraBetul** [comment]
Hi Mr. Aronson, 

You know the semesters end on Monday. Could you please read my project and let me know if there is something wrong with. So I can fix it before the semester ends and then you can fix my grade on the website.

**Comment by KewTeacher** [comment]
Very nice.
